insert into genres values ( 1, 'Crimen/Drama', 1, null, null);
insert into genres values ( 2, 'Drama', 1, null, null);
insert into genres values ( 3, 'Acci�n/ Ciencia Ficci�n', 1, null, null);
insert into genres values ( 4, 'Drama/Romance', 1, null, null);
insert into genres values ( 5, 'Acci�n', 1, null, NULL);
insert into genres values ( 6, 'Suspenso/Drama', 1, null, null);

insert into ORIGIN values (1, 'Estados Unidos', null, NULL);
insert into ORIGIN values (2, 'Reino Unido', null, NULL);
insert into ORIGIN values (3, 'Argentina', null, NULL);
insert into ORIGIN values (4, 'Francia', null, NULL);
insert into ORIGIN values (5, 'Italia', null, NULL);
insert into ORIGIN values (6, 'Espa�a', null, NULL);

insert into CALIFICATION values (1, 'ATP', null, NULL);
insert into CALIFICATION values (2, '+13', null, NULL);
insert into CALIFICATION values (3, '+16', null, NULL);
insert into CALIFICATION values (4, '+18', null, NULL);
insert into CALIFICATION values (5, 'C', null, NULL);

insert into ACTORS values (1, 'Sean', 'Penn', null, null);
insert into ACTORS values (2, 'Kevin', 'Bacon', null, null);
insert into ACTORS values (3, 'Tim', 'Robbins', null, null);
insert into ACTORS values (4, 'Laura', 'Linney', null, null);
insert into ACTORS values (5, 'Daniel', 'Day-Lewis', null, null);
insert into ACTORS values (6, 'Pete', 'Postletwhaite', null, null);
insert into ACTORS values (7, 'Leonardo', 'DiCaprio', null, null);
insert into ACTORS values (8, 'Cameron', 'Diaz', null, null);
insert into ACTORS values (9, 'Liam', 'Neeson', null, null);
insert into ACTORS values (10, 'Naomi', 'Watts', null, null);
insert into ACTORS values (11, 'Benicio', 'Del Toro', null, null);
insert into ACTORS values (12, 'Tom', 'Hardy', null, null);
insert into ACTORS values (13, 'Joseph', 'Gordon-Levitt', null, null);
insert into ACTORS values (14, 'Cillian', 'Murphy', null, null);
insert into ACTORS values (15, 'Haley Joel', 'Osment', null, null);
insert into ACTORS values (16, 'Kevin', 'Spacey', null, null);
insert into ACTORS values (17, 'Helen', 'Hunt', null, null);
insert into ACTORS values (18, 'Al', 'Pacino', null, null);
insert into ACTORS values (19, 'Marlo', 'Brando', null, null);
insert into ACTORS values (20, 'Robert', 'De Niro', null, null);
insert into ACTORS values (21, 'Diane', 'Keaton', null, null);
insert into ACTORS values (22, 'Chris', "O'Donell", null, null);
insert into ACTORS values (23, 'Gabrielle', 'Anwar', null, null);
insert into ACTORS values (24, 'Philip', 'Seymour Hoffman', null, null);
insert into ACTORS values (25, 'Russell', 'Crowe', null, null);
insert into ACTORS values (26, 'Joaquin', 'Phoenix', null, null);
insert into ACTORS values (27, 'Connie', 'Nielsen', null, null);
insert into ACTORS values (28, 'Brad', 'Pitt', null, null);
insert into ACTORS values (29, 'Edward', 'Norton', null, null);

insert into directors values (1, 'Clint', 'Eastwood', null, null);
insert into directors values (2, 'Jim', 'Sheridan', null, null);
insert into directors values (3, 'Martin', 'Scorsese', null, null);
insert into directors values (4, 'Alejandro', 'Gonzalez I�arritu', null, null);
insert into directors values (5, 'Christopher', 'Nolan', null, null);
insert into directors values (6, 'Mimi', 'Leder', null, null);
insert into directors values (7, 'Francis', 'Ford Coppola', null, null);
insert into directors values (8, 'Martin', 'Brest', null, null);
insert into directors values (9, 'Ridley', 'Scott', null, null);
insert into directors values (10, 'David', 'Fincher', null, null);

insert into movies values (1, 'Rio M�stico', 8.5, 137, 1, 1, 2, 'Los viejos amigos de la infancia Jimmy, Sean y Dave se reencuentran de adultos tras el asesinato de la hija de uno de ellos. Las rencillas del pasado envenenan la investigaci�n que, de forma paralela a la polic�a, llevan para hallar al asesino.', null, null, null, null );
insert into movies values (2, 'En el nombre del padre', 9.4, 141, 2, 1, 2, 'Se basa en la historia real de los Cuatro de Guildford, cuatro personas falsamente condenadas por los atentados con bombas en el pub de Guildford de 1974, en los que murieron cuatro soldados brit�nicos fuera de servicio y un civil.', null, null, null, null );
insert into movies values (3, 'Pandilla de New York', 8.7, 125, 1, 1, 2, 'En medio de una guerra civil, la joven naci�n se encuentra al borde del caos. Pero en Five Points, el barrio m�s pobre de Nueva York, donde impera la miseria, la delincuencia y el crimen organizado, se est� librando otra guerra.', null, null, null, null );
insert into movies values (4, '21 gramos', 7.7, 117, 1, 1, 2, 'Paul es un profesor universitario con una dolencia coronaria muy grave. Cristina vive una existencia de cuento de hadas. Y Jack es un exconvicto de fuertes convicciones religiosas que lucha por sacar adelante a su familia.', null, null, null, null );
insert into movies values (5, 'El Orgien', 8.9, 121, 3, 1, 2, 'Dom Cobb es un ladr�n con una extra�a habilidad para entrar a los sue�os de la gente y robarles los secretos de sus subconscientes. Cobb obtiene la oportunidad de redimirse cuando recibe una tarea imposible: plantar una idea en la mente de una persona.', null, null, null, null );
insert into movies values (6, 'Cadena de Favores', 7.9, 107, 4, 1, 2, 'Trevor decide llevar a cabo un experimento para su clase de ciencias sociales bajo una simple premisa: �l har� una serie de favores a tres personas y, a cambio, ellos le devolver�n el favor haciendo algo para otras tres, y as� sucesivamente.', null, null, null, null );
insert into movies values (7, 'El Padrino', 8.7, 181, 1, 1, 2, 'Don Vito Corleone es el respetado y temido jefe de una de las cinco familias de la mafia de Nueva York en los a�os 40. El hombre tiene cuatro hijos: Connie, Sonny, Fredo y Michael, que no quiere saber nada de los negocios sucios de su padre.', null, null, null, null );
insert into movies values (8, 'El Padrino II', 9.1, 185, 1, 1, 2, 'Michael es elegido para liderar los negocios familiares. El nuevo cabeza de familia debe lidiar con un panorama cambiante de amistades y enemistades, al tener que negociar con la mafia jud�a y perder el apoyo de Frankie.', null, null, null, null );
insert into movies values (9, 'El Padrino III', 8.9, 179, 1, 1, 2, 'Michael intenta legitimizar todas las posesiones de la familia negociando con el Vaticano. Despu�s de luchar toda su vida se encuentra cansado y centra todas sus esperanzas en encontrar a un sucesor que se haga cargo de los negocios.', null, null, null, null );
insert into movies values (10, 'Perfume de mujer', 7.9, 157, 2, 1, 2, 'Frank, un militar ciego, emprende un viaje a Nueva York con un joven recluta que le cuida durante Acci�n de Gracias. Frank est� dispuesto a matar a un antiguo compa�ero de armas, y despu�s, suicidarse', null, null, null, null );
insert into movies values (11, 'Gladiador', 8.1, 155, 5, 1, 2, 'El general romano M�ximo es el soporte m�s leal del emperador Marco Aurelio, que lo ha conducido de victoria en victoria. Sin embargo, C�modo, el hijo de Marco Aurelio, est� celoso del prestigio de M�ximo y a�n m�s del amor que su padre siente por �l.', null, null, null, null );
insert into movies values (12, 'El club del a pelea', 8.3, 139, 6, 1, 2, 'Un empleado de oficina insomne, harto de su vida, se cruza con un vendedor peculiar. Ambos crean un club de lucha clandestino como forma de terapia y, poco a poco, la organizaci�n crece y sus objetivos toman otro rumbo.', null, null, null, null );

insert into actor_movie values (1, 1 ,1, null, null);
insert into actor_movie values (2, 2 ,1, null, null);
insert into actor_movie values (3, 3 ,1, null, null);
insert into actor_movie values (4, 4 ,1, null, null);
insert into actor_movie values (5, 5 ,2, null, null);
insert into actor_movie values (6, 6 ,2, null, null);
insert into actor_movie values (7, 6 ,3, null, null);
insert into actor_movie values (8, 7 ,3, null, null);
insert into actor_movie values (9, 8 ,3, null, null);
insert into actor_movie values (37, 9 ,3, null, null);
insert into actor_movie values (10, 1 ,4, null, null);
insert into actor_movie values (11, 10 ,4, null, null);
insert into actor_movie values (12, 11 ,4, null, null);
insert into actor_movie values (13, 7 ,5, null, null);
insert into actor_movie values (14, 12 ,5, null, null);
insert into actor_movie values (15, 13 ,5, null, null);
insert into actor_movie values (16, 14 ,5, null, null);
insert into actor_movie values (17, 15 ,6, null, null);
insert into actor_movie values (18, 16 ,6, null, null);
insert into actor_movie values (19, 17 ,6, null, null);
insert into actor_movie values (20, 18 ,7, null, null);
insert into actor_movie values (21, 19 ,7, null, null);
insert into actor_movie values (22, 20 ,7, null, null);
insert into actor_movie values (23, 21 ,7, null, null);
insert into actor_movie values (24, 18 ,8, null, null);
insert into actor_movie values (25, 19 ,8, null, null);
insert into actor_movie values (26, 20 ,8, null, null);
insert into actor_movie values (27, 21 ,8, null, null);
insert into actor_movie values (28, 18 ,9, null, null);
insert into actor_movie values (29, 20 ,9, null, null);
insert into actor_movie values (30, 21 ,9, null, null);
insert into actor_movie values (31, 18 ,10, null, null);
insert into actor_movie values (32, 22 ,10, null, null);
insert into actor_movie values (33, 23 ,10, null, null);
insert into actor_movie values (34, 24 ,10, null, null);
insert into actor_movie values (35, 25 ,11, null, null);
insert into actor_movie values (36, 26 ,11, null, null);
insert into actor_movie values (38, 27 ,11, null, null);
insert into actor_movie values (39, 28 ,12, null, null);
insert into actor_movie values (40, 29 ,12, null, null);

insert into director_movie values (1, 1 , 1, null, null);
insert into director_movie values (2, 2 , 2, null, null);
insert into director_movie values (3, 3 , 3, null, null);
insert into director_movie values (4, 4 , 4, null, null);
insert into director_movie values (5, 5 , 5, null, null);
insert into director_movie values (6, 6 , 6, null, null);
insert into director_movie values (7, 7 , 7, null, null);
insert into director_movie values (8, 8 , 7, null, null);
insert into director_movie values (9, 9 , 7, null, null);
insert into director_movie values (10, 10 , 8, null, null);
insert into director_movie values (11, 11 , 9, null, null);
insert into director_movie values (12, 12 , 10, null, null);

insert into category values (1, 'Administrador', null, null);
insert into category values (2, 'Usuario', null, null);

insert into users values (1, 'Ignacio', 'Fabiani', 'ignacio@gmail.com', 'ignacio123', '1987-07-02', 1, null, null);
insert into users values (2, 'Thomas', 'Whitney', 'thomas@gmail.com', 'thomas123', '1985-01-01', 1, null, null);
insert into users values (3, 'Marcos', 'Corti', 'marcos@gmail.com', 'marcos123', '1985-01-01', 1, null, null);
insert into users values (4, 'Juan Manuel', 'Pedrozo', 'juanmanuel@gmail.com', 'juanmanuel123', '1985-01-01', 1, null, null);

update movies set image = 'pelicula-1' where id=1;
update movies set image = 'pelicula-2' where id=2;
update movies set image = 'pelicula-3' where id=3;
update movies set image = 'pelicula-4' where id=4;
update movies set image = 'pelicula-5' where id=5;
update movies set image = 'pelicula-6' where id=6;
update movies set image = 'pelicula-7' where id=7;
update movies set image = 'pelicula-8' where id=8;
update movies set image = 'pelicula-9' where id=9;
update movies set image = 'pelicula-10' where id=10;
update movies set image = 'pelicula-11' where id=11;
update movies set image = 'pelicula-12' where id=12;

update users set image = 'usuario-5' where id=1;
update users set image = 'usuario-5' where id=2;
update users set image = 'usuario-5' where id=3;
update users set image = 'usuario-5' where id=4;
update users set image = 'usuario-5' where id=5;
update users set image = 'usuario-5' where id=17;

